# Post-C137 epoch closure — C138–C145

Base9f335df9dc04184242a0a6c52dfca4784912a5fa, same research branch/epoch post-c119-20260929T133115Z, deadline2026-09-30T01:31:15Z. Owner publication pause remained included; no new epoch or remote write. See results/c145-post-c137-closure-20260930T0019Z/decision.json for full source/freeze/measurement/result SHAs, manifest hashes and authority.

## Result and boundaries

C138 strengthened trace gates pass original C135/C136 raws and expose/reject the three reviewer counterexamples;17 relevant model-free tests PASS. Explicit48-call segmentation and CPU0–24/GPU25–35 mapping retained. Decode6624 demands/1077loads and8.753159s WAIT union remain measured intervals, not removable-time/physical traffic. Zero decode later-demand autoevictions. Faithful primary replay is NOT_IDENTIFIABLE without initial hotness/recency/global decay/slot/commit state. Cold LRU/offline min-load simulations are explicitly conditional, not warm latency bounds.

C139 refused E20 before model; owner freed RAM. C140 then admitted E20 and uniform44 passed OFF/ON bitwise selected states/five logits plus36 canonical FFN. GPU peak7450MiB<7676 guard; no capacity/numeric failure or fallback required. These gates cover189+32 and specific FFN activations, not a complete8K model proof.

C141 screen PASS in two pairs. C142 CONFIRMED_UNIFORM44_NOMINAL153 in three fresh pairs: warm decode gain11.745365%, warm first-final8.575215%, all primary pairs positive and all five protected medians>=−5%. Exact official IDs/complete messages/natural78/47 tokens match within pairs. Original C75 binary/libraries, P12/medium/8192/ub32 and common E20; only40→44 slots changes. Addition by tier1,321,920,000B CPU/581,644,800B GPU. Actual median warm decode8.976260s/5.236034tok/s and first-final19.312233s. The alternated operational test does not exclusively attribute gain to NVMe/hits or generalize a working-set law.

C143 delivers original slots40 opt-in plus explicit C35 fallback, complete commands/requirements/date/session/cache/stop instructions in research/C143-SLOTS40-OPTIN-20260930.md. Five relevant tests PASS (actual builder, real spawn gate positive/seven negatives, PID reuse rejection/owner stop). Real no-weight smoke passed E18/swap0/fresh60s/actual process and mapped library checks. First smoke omitted required empty limits metadata and failed before inventory/model; original protocol/receipt preserved, builder regression added before smoke02. Actual live preset prepared but not started; full launcher model session is NOT_RUN.

Coverage40:12/12 quality,8/8 holdout,20 natural varied requests83.3min/31min active with strict19/20 gate, retrieval7936/85natural output/cap256. C133 turn02 lexicalAster omission preserved; no material semantic loss demonstrated in this turn, no regrade or repeated83min run. M3 remains partial.44 does not inherit quality/session/retrieval; its broader coverage NOT_RUN. M4 NOT_DEMONSTRATED (5.24<6tok/s,19.31>10s; cold~2K is not cold512, prefix4096 gate not certified). Conditional fixed-work decode reduction still needed to6 is12.73%; this is arithmetic, not a speedup forecast.

C144 source-only capability matrix at upstream8019dc563b1ecbae6b161a70c3a1359f1b206c1e extends C116, with pinned primary sources/file hashes. A mmap-backed CPU-expert/GPU-attention path warrants a separate bounded canary, not a promise of support/performance or a new physical run now. Explicit per-expert bounded streaming for this target is not established at that pin. Next retention discriminator is a bounded full state snapshot/replay and independent routing, before any quota/cache manager investment. No automatic44/46/48 grid, eviction change or fallback after this successful intervention.

## Ledger and closure

Physical conservative charge24232.829s, remaining lower estimate4567.171s; wall remaining at ledger4225.073s, pauses included. This epoch closes because the permitted intervention and useful opt-in delivery are complete and no further physical discriminator is justified/authorized, not because the budget was exhausted. Individual process/server/request times are separate; prior upper bounds and unrecorded inventory query envelopes are ESTIMADO. C139 inherited checkpoint-link and baseline-only60s accounting errata are append-only in the ledger, no historical receipt replaced.

Unique raw bytes across this epoch487083578 (about0.454GiB)<20GiB. Per-unit manifests plus raw-epoch-manifest.json preserve hashes; raw/model/build stay local. No model process or own experimental scope remains; GPU12MiB, opt-in port free. main/default/ordinary service unchanged. Branch remote remains9f335df…; all new commits are LOCAL_ONLY and ready to review. No push/PR/merge/force-push. All prior FAIL/NO_GO/owner interruptions, C137 NOT_RUN and new premodel failures remain.
